export default {
	//region Dashboard events
	REFRESH_ACTIVE_TAB: 'REFRESH_ACTIVE_TAB',
	REFRESH_ALL: 'REFRESH_ALL',
	COMPONENT_OUTPUT_ACTIVE_OBJECT_CHANGE:
		'COMPONENT_OUTPUT_ACTIVE_OBJECT_CHANGE',
	COMPONENT_OUTPUT_CHANGE: 'COMPONENT_OUTPUT_CHANGE',
	CLEAR_ACTIVE_TAB_USE_FROM_ABOVE_FILTERS:
		'CLEAR_ACTIVE_TAB_USE_FROM_ABOVE_FILTERS',
	COMPONENTS_SIZES_CHANGED: 'COMPONENTS_SIZES_CHANGED',

	// events for report viewer based components (e.g. report viewer, matrix etc.)
	ATTRIBUTE_DATA_SERVICE_INITIALIZED: 'ATTRIBUTE_DATA_SERVICE_INITIALIZED',
	VIEWER_TABLE_COLUMNS_CHANGED: 'VIEWER_TABLE_COLUMNS_CHANGED',
	SAVE_VIEWER_TABLE_CONFIGURATION: 'SAVE_VIEWER_TABLE_CONFIGURATION',
	//endregion

	//region Dashboard component events
	COMPONENT_STATUS_CHANGE: 'COMPONENT_STATUS_CHANGE',
	RELOAD_COMPONENT: 'RELOAD_COMPONENT',
	RELOAD_CONTENT_OF_COMPONENT: 'RELOAD_CONTENT_OF_COMPONENT',

	CLEAR_USE_FROM_ABOVE_FILTERS: 'CLEAR_USE_FROM_ABOVE_FILTERS',
	UPDATE_VIEWER_TABLE_COLUMNS: 'UPDATE_VIEWER_TABLE_COLUMNS',
	TOGGLE_FILTER_BLOCK: 'TOGGLE_FILTER_BLOCK',

	OPEN_COMPONENT_EDITOR: 'OPEN_COMPONENT_EDITOR',

	COMPONENT_BLOCKAGE_ON: 'COMPONENT_BLOCKAGE_ON',
	COMPONENT_BLOCKAGE_OFF: 'COMPONENT_BLOCKAGE_OFF',

	REPORT_VIEWER_DATA_SERVICE_SET: 'REPORT_VIEWER_DATA_SERVICE_SET',

	RESIZE: 'RESIZE',

	DASHBOARD_LAYOUT_CHANGE: 'DASHBOARD_LAYOUT_CHANGE',
	TOGGLE_SHOW_FROM_ABOVE_FILTERS: 'TOGGLE_SHOW_FROM_ABOVE_FILTERS',

	COMPONENT_DATA_CHANGED_INSIDE: 'COMPONENT_DATA_CHANGED_INSIDE',
	//endregion
}
