export default {
	MODEL_CHANGED_FROM_OUTSIDE: 'MODEL_CHANGED_FROM_OUTSIDE',

	//region chipsListDirective
	CHIPS_LIST_CHANGED: 'CHIPS_LIST_CHANGED',
	CHIPS_LIST_ELEMENT_SIZE_CHANGED: 'CHIPS_LIST_ELEMENT_SIZE_CHANGED',
	DROPDOWN_MENU_OPTIONS_CHANGED: 'DROPDOWN_MENU_OPTIONS_CHANGED',
	//endregion

	//region classifierTreeDirective
	TREE_CHANGED_FROM_OUTSIDE: 'TREE_CHANGED_FROM_OUTSIDE',
	EDIT_NODE: 'EDIT_NODE',
	CANCEL_EDIT_NODE: 'CANCEL_EDIT_NODE',
	DELETE_NODE: 'DELETE_NODE',
	ADD_NODE: 'ADD_NODE',
	CLASSIFIER_TREE_CHANGED: 'CLASSIFIER_TREE_CHANGED',
	//endregion

	//region multitypeFieldDirective
	FIELD_TYPES_DATA_CHANGED: 'FIELD_TYPES_DATA_CHANGED',
	//endregion

	//region entityNamesFieldDirective, multiinputFieldDirective
	TURN_ON_ERROR_MODE: 'TURN_ON_ERROR_MODE',
	TURN_OFF_ERROR_MODE: 'TURN_OFF_ERROR_MODE',
	//endregion
}
