// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'TheHeader': typeof import("../src/components/TheHeader.vue")['default'],
    'TheSidebar': typeof import("../src/components/TheSidebar.vue")['default'],
    'BaseButton': typeof import("../src/components/base/Button.vue")['default'],
    'BaseInput': typeof import("../src/components/base/Input.vue")['default'],
    'BasePopup': typeof import("../src/components/base/Popup.vue")['default'],
    'BaseTable': typeof import("../src/components/base/Table.vue")['default'],
    'PagesProfileBackups': typeof import("../src/components/pages/profile/Backups.vue")['default'],
    'PagesProfileBilling': typeof import("../src/components/pages/profile/Billing.vue")['default'],
    'PagesProfileDatabases': typeof import("../src/components/pages/profile/Databases.vue")['default'],
    'PagesProfileDatabasesItem': typeof import("../src/components/pages/profile/DatabasesItem.vue")['default'],
    'PagesProfileInviteItem': typeof import("../src/components/pages/profile/InviteItem.vue")['default'],
    'PagesProfileSettings': typeof import("../src/components/pages/profile/Settings.vue")['default'],
    'PagesProfileTwoFAModal': typeof import("../src/components/pages/profile/TwoFAModal.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyTheHeader': typeof import("../src/components/TheHeader.vue")['default'],
    'LazyTheSidebar': typeof import("../src/components/TheSidebar.vue")['default'],
    'LazyBaseButton': typeof import("../src/components/base/Button.vue")['default'],
    'LazyBaseInput': typeof import("../src/components/base/Input.vue")['default'],
    'LazyBasePopup': typeof import("../src/components/base/Popup.vue")['default'],
    'LazyBaseTable': typeof import("../src/components/base/Table.vue")['default'],
    'LazyPagesProfileBackups': typeof import("../src/components/pages/profile/Backups.vue")['default'],
    'LazyPagesProfileBilling': typeof import("../src/components/pages/profile/Billing.vue")['default'],
    'LazyPagesProfileDatabases': typeof import("../src/components/pages/profile/Databases.vue")['default'],
    'LazyPagesProfileDatabasesItem': typeof import("../src/components/pages/profile/DatabasesItem.vue")['default'],
    'LazyPagesProfileInviteItem': typeof import("../src/components/pages/profile/InviteItem.vue")['default'],
    'LazyPagesProfileSettings': typeof import("../src/components/pages/profile/Settings.vue")['default'],
    'LazyPagesProfileTwoFAModal': typeof import("../src/components/pages/profile/TwoFAModal.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const TheHeader: typeof import("../src/components/TheHeader.vue")['default']
export const TheSidebar: typeof import("../src/components/TheSidebar.vue")['default']
export const BaseButton: typeof import("../src/components/base/Button.vue")['default']
export const BaseInput: typeof import("../src/components/base/Input.vue")['default']
export const BasePopup: typeof import("../src/components/base/Popup.vue")['default']
export const BaseTable: typeof import("../src/components/base/Table.vue")['default']
export const PagesProfileBackups: typeof import("../src/components/pages/profile/Backups.vue")['default']
export const PagesProfileBilling: typeof import("../src/components/pages/profile/Billing.vue")['default']
export const PagesProfileDatabases: typeof import("../src/components/pages/profile/Databases.vue")['default']
export const PagesProfileDatabasesItem: typeof import("../src/components/pages/profile/DatabasesItem.vue")['default']
export const PagesProfileInviteItem: typeof import("../src/components/pages/profile/InviteItem.vue")['default']
export const PagesProfileSettings: typeof import("../src/components/pages/profile/Settings.vue")['default']
export const PagesProfileTwoFAModal: typeof import("../src/components/pages/profile/TwoFAModal.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyTheHeader: typeof import("../src/components/TheHeader.vue")['default']
export const LazyTheSidebar: typeof import("../src/components/TheSidebar.vue")['default']
export const LazyBaseButton: typeof import("../src/components/base/Button.vue")['default']
export const LazyBaseInput: typeof import("../src/components/base/Input.vue")['default']
export const LazyBasePopup: typeof import("../src/components/base/Popup.vue")['default']
export const LazyBaseTable: typeof import("../src/components/base/Table.vue")['default']
export const LazyPagesProfileBackups: typeof import("../src/components/pages/profile/Backups.vue")['default']
export const LazyPagesProfileBilling: typeof import("../src/components/pages/profile/Billing.vue")['default']
export const LazyPagesProfileDatabases: typeof import("../src/components/pages/profile/Databases.vue")['default']
export const LazyPagesProfileDatabasesItem: typeof import("../src/components/pages/profile/DatabasesItem.vue")['default']
export const LazyPagesProfileInviteItem: typeof import("../src/components/pages/profile/InviteItem.vue")['default']
export const LazyPagesProfileSettings: typeof import("../src/components/pages/profile/Settings.vue")['default']
export const LazyPagesProfileTwoFAModal: typeof import("../src/components/pages/profile/TwoFAModal.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
