export default {
	COLUMNS_CHANGE: 'COLUMNS_CHANGE',
	FILTERS_CHANGE: 'FILTERS_CHANGE',
	FILTERS_TO_SHOW_CHANGE: 'FILTERS_TO_SHOW_CHANGE', // entity viewer filters to show (front or back) switched
	GROUPS_CHANGE: 'GROUPS_CHANGE',
	CLEAR_USE_FROM_ABOVE_FILTERS: 'CLEAR_USE_FROM_ABOVE_FILTERS',
	FILTERS_RENDERED: 'FILTERS_RENDERED',

	UPDATE_TABLE: 'UPDATE_TABLE', // async download
	REDRAW_TABLE: 'REDRAW_TABLE', // inmemory redraw
	UPDATE_PROJECTION: 'UPDATE_PROJECTION',
	FINISH_RENDER: 'FINISH_RENDER',

	PAGE_CHANGE: 'PAGE_CHANGE',
	ADDITIONS_CHANGE: 'ADDITIONS_CHANGE',
	DYNAMIC_ATTRIBUTES_CHANGE: 'DYNAMIC_ATTRIBUTES_CHANGE',

	RESIZE_COLUMNS_START: 'RESIZE_COLUMNS_START',
	RESIZE_COLUMNS_END: 'RESIZE_COLUMNS_END',

	TABLE_CHART_COLUMN_RESIZE_END: 'TABLE_CHART_COLUMN_RESIZE_END',

	UPDATE_COLUMNS_SIZE: 'UPDATE_COLUMNS_SIZE',
	UPDATE_TABLE_HEAD_COLUMNS_SIZE: 'UPDATE_TABLE_HEAD_COLUMNS_SIZE',
	START_CELLS_OVERFLOW: 'START_CELLS_OVERFLOW',

	REQUEST_REPORT: 'REQUEST_REPORT',
	DATA_LOAD_END: 'DATA_LOAD_END',
	DATA_LOAD_START: 'DATA_LOAD_START',

	ACTIVE_OBJECT_CHANGE: 'ACTIVE_OBJECT_CHANGE', // right click on object info
	USER_REQUEST_AN_ACTION: 'USER_REQUEST_AN_ACTION', // user used a Add menu and want to Add Entity (portfolio, account,  etc)
	ACTIVE_OBJECT_FROM_ABOVE_CHANGE: 'ACTIVE_OBJECT_FROM_ABOVE_CHANGE', // for active object for split panel from root entity viewer

	ROWS_ACTION_FIRED: 'ROWS_ACTION_FIRED',

	COLUMN_SORT_CHANGE: 'COLUMN_SORT_CHANGE',
	GROUP_TYPE_SORT_CHANGE: 'GROUP_TYPE_SORT_CHANGE',

	GROUPS_LEVEL_FOLD: 'GROUPS_LEVEL_FOLD',
	GROUPS_LEVEL_UNFOLD: 'GROUPS_LEVEL_UNFOLD',

	UPDATE_EV_UI: 'UPDATE_EV_UI',
	TOGGLE_FILTER_AREA: 'TOGGLE_FILTER_AREA',
	TOGGLE_FILTER_BLOCK: 'TOGGLE_FILTER_BLOCK',
	UPDATE_FILTER_AREA_SIZE: 'UPDATE_FILTER_AREA_SIZE',
	TOGGLE_SHOW_FROM_ABOVE_FILTERS: 'TOGGLE_SHOW_FROM_ABOVE_FILTERS',

	UPDATE_TABLE_VIEWPORT: 'UPDATE_TABLE_VIEWPORT', // recalculate height and width for ev-viewport
	UPDATE_ENTITY_VIEWER_CONTENT_WRAP_SIZE:
		'UPDATE_ENTITY_VIEWER_CONTENT_WRAP_SIZE',
	TABLE_SIZES_CALCULATED: 'TABLE_SIZES_CALCULATED',

	REPORT_OPTIONS_CHANGE: 'REPORT_OPTIONS_CHANGE',
	TOGGLE_USE_REPORT_DATE_FROM_ABOVE: 'TOGGLE_USE_REPORT_DATE_FROM_ABOVE',

	LIST_LAYOUT_CHANGE: 'LIST_LAYOUT_CHANGE',
	DEFAULT_LAYOUT_CHANGE: 'DEFAULT_LAYOUT_CHANGE',
	ACTIVE_LAYOUT_CONFIGURATION_CHANGED: 'ACTIVE_LAYOUT_CONFIGURATION_CHANGED', // fires on DATA_LOAD_END
	LAYOUT_NAME_CHANGE: 'LAYOUT_NAME_CHANGE',

	//region Events used only to track layout changes
	REPORT_EXPORT_OPTIONS_CHANGED: 'REPORT_EXPORT_OPTIONS_CHANGED',
	REPORT_TABLE_VIEW_CHANGED: 'REPORT_TABLE_VIEW_CHANGED',
	ENTITY_VIEWER_PAGINATION_CHANGED: 'ENTITY_VIEWER_PAGINATION_CHANGED',
	ENTITY_VIEWER_SETTINGS_CHANGED: 'ENTITY_VIEWER_SETTINGS_CHANGED',
	//endregion Events used only to track layout changes

	//region Trigger Split Panel events from root entity viewer
	UPDATE_SPLIT_PANEL_TABLE_VIEWPORT: 'UPDATE_SPLIT_PANEL_TABLE_VIEWPORT',
	SPLIT_PANEL_DEFAULT_LIST_LAYOUT_CHANGED:
		'SPLIT_PANEL_DEFAULT_LIST_LAYOUT_CHANGED',
	TOGGLE_AUTOSAVE: 'TOGGLE_AUTOSAVE',

	VIEW_TYPE_CHANGED: 'VIEW_TYPE_CHANGED',

	VERTICAL_ADDITIONS_CHANGE: 'VERTICAL_ADDITIONS_CHANGE',

	RECON_BOOK_SELECTED: 'RECON_BOOK_SELECTED',
	//endregion Trigger Split Panel events from root entity viewer

	// Trigger Entity Viewer methods from Split Panel
	RECON_TOGGLE_MATCH_EDITOR: 'RECON_TOGGLE_MATCH_EDITOR',
	// < Trigger Entity Viewer methods from Split Panel >

	//region When inside dashboard events
	OPEN_DASHBOARD_COMPONENT_EDITOR: 'OPEN_DASHBOARD_COMPONENT_EDITOR',
	MISSING_PRICES_LOAD_END_TO_DASHBOARD: 'MISSING_PRICES_LOAD_END_TO_DASHBOARD',
	DASHBOARD_COMPONENT_DATA_CHANGED: 'DASHBOARD_COMPONENT_DATA_CHANGED',
	//endregion

	MISSING_PRICES_LOAD_END: 'MISSING_PRICES_LOAD_END',

	ROW_ACTIVATION_CHANGE: 'ROW_ACTIVATION_CHANGE',
	HIDE_BULK_ACTIONS_AREA: 'HIDE_BULK_ACTIONS_AREA',
}
