<template>
	 <v-dialog>
			<v-card max-width="526">
				<v-card-title>
					Two-factor authentication
				</v-card-title>

				<template v-if="step == 'start'">
					<v-card-text>
						Two-factor authentication adds an extra layout of protection to your account. Whenever you sign in to the Finmars you will need to enter both your password and a security code on your mobile phone.
					</v-card-text>
					<v-card-actions class="space-between">
						<v-btn color="primary" @click="close()">cancel</v-btn>
						<v-btn color="primary" variant="contained" @click="step = 'scan'">next</v-btn>
					</v-card-actions>
				</template>

				<template v-if="step == 'scan'">
					<v-card-text>
						An authenticator app lets you generate security codes on your mobile phone.
					</v-card-text>
					<v-card-text>
						To configure your authenticator app:
						<br>
						<br>
						<ul>
							<li>- Add a new time-based token</li>
							<li>- Use your app to scan the QR code below</li>
						</ul>
					</v-card-text>
					<div class="center">
						<vue-qrcode :value="qrLink" :options="{ width: 236, border: 0 }" />
					</div>
					<div class="center">
						<v-btn variant="text" color="primary" @click="isShowApps = !isShowApps">Show authenticator Apps</v-btn>
					</div>
					<v-card-text class="pt-0" v-if="isShowApps">
						<ul>
							<li class="d-flex space-between align-center auth_app_item">
								<div>
									<img width="33" src="img/g-auth-app.svg" alt="">
									Google authenticator
								</div>
								<div class="d-flex align-center">
									<a href="https://apps.apple.com/us/app/google-authenticator/id388497605" target="_blank"><img width="112" src="img/app-store.png" alt=""></a>
									<a href="https://play.google.com/useStore/apps/details?id=com.google.android.apps.authenticator2" target="_blank"><img width="112" src="img/google-play.png" alt=""></a>
								</div>
							</li>
							<li class="d-flex space-between align-center auth_app_item">
								<div>
									<img width="33" src="img/microsoft-authenticator.svg" alt="">
									Microsoft authenticator
								</div>
								<div class="d-flex align-center">
									<a href="https://apps.apple.com/us/app/microsoft-authenticator/id983156458" target="_blank"><img width="112" src="img/app-store.png" alt=""></a>
									<a href="https://play.google.com/useStore/apps/details?id=com.azure.authenticator" target="_blank"><img width="112" src="img/google-play.png" alt=""></a>
								</div>
							</li>
						</ul>
					</v-card-text>
					<v-card-actions class="space-between">
						<v-btn color="primary" @click="close()">cancel</v-btn>
						<v-btn color="primary" variant="contained" @click="step = 'finish'">next</v-btn>
					</v-card-actions>
				</template>

				<template v-if="step == 'finish'">
					<v-card-text>
						Enter the security code generated by your authenticator app to make sure it's configured correctly
					</v-card-text>
					<v-card-text>
						<v-text-field
							label="Security code"
							placeholder="Security code"
							variant="outlined"
							density="comfortable"
							hint="At least 6 numbers"
							v-model="code"
							@input="validateCode()"
						/>
					</v-card-text>

					<v-card-actions class="space-between">
						<v-btn color="primary" @click="step = 'scan'">back</v-btn>
						<v-btn color="primary" variant="contained" @click="close()">finish</v-btn>
					</v-card-actions>
				</template>

			</v-card>
		</v-dialog>
</template>

<script setup>
	let emit = defineEmits(['close'])
	let step = ref('start')
	let isShowApps = ref(false)
	let code = ref('')

	let res = await useApi('generateQR.put')
	let qrLink = res.provisioning_uri

	async function validateCode() {
		if ( !code.value || code.value.length < 6 ) return false

		let res = await useApi('validateQR.put', {
			body: {code: code.value, username: useState('user').value.username}
		})

		if ( res.match ) {
			addDevice( res.id )
		}
	}
	async function addDevice( id ) {
		let res = await useApi('meTwoFactor.patch', {
			body: {is_active: true},
			params: { id },
		})

		if ( res ) {
			close()
		}
	}
	async function close() {
		step.value = 'start'
		isShowApps.value = false
		code.value = ''
		emit('close')
	}

</script>

<style lang="sass" scoped>
.auth_app_item
	padding: 19px 0
	border-bottom: 1px solid #E0E0E0

</style>
