<template>
	 <BaseModal title="Two-factor authentication">

		<p class="modal_container" style="margin-bottom: 15px;" v-if="step == 'start'">
			Two-factor authentication adds an extra layout of protection to your account. Whenever you sign in to the Finmars you will need to enter both your password and a security code on your mobile phone.
		</p>

		<template v-if="step == 'scan'">
			An authenticator app lets you generate security codes on your mobile phone.
			<br>
			<br>
			To configure your authenticator app:
			<br>
			<br>
			<ul>
				<li>- Add a new time-based token</li>
				<li>- Use your app to scan the QR code below</li>
			</ul>
			<div class="flex jcc">
				<vue-qrcode :value="qrLink" :options="{ width: 236, border: 0 }" />
			</div>
			<div class="flex jcc">
				<FmBtn class="mb-15" type="action" @click="isShowApps = !isShowApps">
					{{ isShowApps ? 'Hide' : 'Show' }} authenticator Apps
				</FmBtn>
			</div>
			<div v-if="isShowApps">
				<ul>
					<li class="flex sb aic auth_app_item">
						<div>
							<img width="33" src="img/g-auth-app.svg" alt="">
							Google authenticator
						</div>
						<div class="flex center">
							<a href="https://apps.apple.com/us/app/google-authenticator/id388497605" target="_blank"><img width="112" src="img/app-store.png" alt=""></a>
							<a href="https://play.google.com/useStore/apps/details?id=com.google.android.apps.authenticator2" target="_blank"><img width="112" src="img/google-play.png" alt=""></a>
						</div>
					</li>
					<li class="flex sb aic auth_app_item">
						<div>
							<img width="33" src="img/microsoft-authenticator.svg" alt="">
							Microsoft authenticator
						</div>
						<div class="d-flex align-center">
							<a href="https://apps.apple.com/us/app/microsoft-authenticator/id983156458" target="_blank"><img width="112" src="img/app-store.png" alt=""></a>
							<a href="https://play.google.com/useStore/apps/details?id=com.azure.authenticator" target="_blank"><img width="112" src="img/google-play.png" alt=""></a>
						</div>
					</li>
				</ul>
			</div>
		</template>

		<div class="modal_container" v-if="step == 'finish'">
			Enter the security code generated by your authenticator app to make sure it's configured correctly
			<br>
			<br>
			<BaseInput
				label="Security code"
				v-model="code"
				@input="validateCode()"
			/>
		</div>

		<template #controls>
			<div class="flex sb">
				<FmBtn v-if="step != 'finish'" type="text" @click="close()">cancel</FmBtn>
				<FmBtn v-else type="text" @click="step = 'scan'">back</FmBtn>

				<FmBtn v-if="step == 'start'" @click="step = 'scan'">next</FmBtn>
				<FmBtn v-if="step == 'scan'" @click="step = 'finish'">next</FmBtn>
				<FmBtn v-if="step == 'finish'" @click="close(false)">finish</FmBtn>
			</div>

		</template>
	</BaseModal>
</template>

<script setup>
	let emit = defineEmits(['close'])
	let step = ref('start')
	let isShowApps = ref(false)
	let code = ref('')

	let res = await useApi('generateQR.put')
	let qrLink = res.provisioning_uri

	async function validateCode() {
		if ( !code.value || code.value.length < 6 ) return false

		let res = await useApi('validateQR.put', {
			body: {code: code.value, username: 'test'}
		})

		if ( res.match ) {
			console.log('res.match:', res.match)
			addDevice( res.id )
		}
	}
	async function addDevice( id ) {
		let res = await useApi('meTwoFactor.patch', {
			body: {is_active: true},
			params: { id },
		})

		if ( res ) {
			close()
		}
	}
	async function close( success = true  ) {
		step.value = 'start'
		isShowApps.value = false
		code.value = ''
		emit('close', success)
	}

</script>

<style lang="scss" scoped>
.auth_app_item {
	padding: 19px 0;

	& + & {
		border-top: 1px solid #E0E0E0;
	}
	&:last-child {
		margin-bottom: 15px;
	}
}
.mb-15 {
	margin-bottom: 15px !important;
}
.modal_container {
	max-width: 486px;
}
</style>
