export default {
	FIELD_CHANGED: 'FIELD_CHANGED',
	MARK_FIELDS_WITH_ERRORS: 'MARK_FIELDS_WITH_ERRORS',

	FIELDS_RECALCULATION_START: 'FIELDS_RECALCULATION_START',
	FIELDS_RECALCULATION_END: 'FIELDS_RECALCULATION_END',

	DYNAMIC_ATTRIBUTES_CHANGE: 'DYNAMIC_ATTRIBUTES_CHANGE',

	TABLE_INSTANCE_CHANGED: 'TABLE_INSTANCE_CHANGED', // for tables with multiple instances on a form (e.g. accruals schedules, events for instrument's form)
	ENTITY_UPDATED: 'ENTITY_UPDATED',
}
